### ISSUE TITLE
Error when building on Windows

### ISSUE THREAD

**Issue by unindented** [atom-archive/electron-starter#30]
I'm getting this error when running on Windows:

```
C:\Users\Daniel\Downloads\atom-shell-starter>script\bootstrap.cmd
Node: v0.10.35
npm: v1.4.28
Python: v2.7.9
Installing build modules...
Installing apm...
npm WARN package.json github-url-from-git@1.1.1 No repository field.
Installing modules done
Deduping modules done
C:\Users\Daniel\Downloads\atom-shell-starter>script\build.cmd
Node: v0.10.35
npm: v1.4.28
Python: v2.7.9
Installing build modules...
Installing apm...
Installing modules done
Deduping modules done
Running "build-atom-shell" task
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 127, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 34, in main
>>     update_atom_shell()
>>   File "script/bootstrap.py", line 123, in update_atom_shell
>>     execute_stdout([sys.executable, update])
>>   File "C:\Users\Daniel\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 150, in execute_st
dout
>>     execute(argv)
>>   File "C:\Users\Daniel\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 138, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\Daniel\\AppData\\Local\\Temp\\eighto
height-build\\atom-shell\\script\\update.py']' returned non-zero exit status 1
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 127, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 34, in main
>>     update_atom_shell()
>>   File "script/bootstrap.py", line 123, in update_atom_shell
>>     execute_stdout([sys.executable, update])
>>   File "C:\Users\Daniel\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 150, in execute_st
dout
>>     execute(argv)
>>   File "C:\Users\Daniel\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 138, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\Daniel\\AppData\\Local\\Temp\\eighto
height-build\\atom-shell\\script\\update.py']' returned non-zero exit status 1
Aborted due to warnings.
```

Running `script\update.py` manually throws this error:

```
C:\Users\Daniel\AppData\Local\Temp\atom-shell>python C:\Users\Daniel\AppData\Local\Temp\atom-shell\script\update.py
Traceback (most recent call last):
  File "script\update-external-binaries.py", line 66, in <module>
    sys.exit(main())
  File "script\update-external-binaries.py", line 31, in main
    download_and_unzip('directxsdk')
  File "script\update-external-binaries.py", line 50, in download_and_unzip
    zip_path = download_framework(framework)
  File "script\update-external-binaries.py", line 61, in download_framework
    download('Download ' + framework, url, path)
  File "C:\Users\Daniel\AppData\Local\Temp\atom-shell\script\lib\util.py", line 48, in download
    web_file = urllib2.urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Temp\atom-shell\script\update.py", line 50, in <module>
    sys.exit(main())
  File "C:\Users\Daniel\AppData\Local\Temp\atom-shell\script\update.py", line 16, in main
    update_external_binaries()
  File "C:\Users\Daniel\AppData\Local\Temp\atom-shell\script\update.py", line 22, in update_external_binaries
    subprocess.check_call([sys.executable, uf])
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'script\\update-external-binaries.py']' returned no
n-zero exit status 1
```

Looks like that `SSL: CERTIFICATE_VERIFY_FAILED` is what's causing the error? Have you ever encountered this @paulcbetts?

**Comment by paulcbetts** [comment]
This is a change in Python that caused an issue with a certain range of Atom Shell, you can fix it by downgrading to the version of Python 2.7 released last June

**Comment by unindented** [comment]
Super useful, I'll try that when I get home. Thanks!

**Comment by paulcbetts** [comment]
@unindented Basically in 2.7.7, they added SSL cert verification (good idea!), but then they shipped an outdated root cert list and don't use the system list, and AWS updated their cert so now it doesn't validate (even though it is a valid cert)

**Comment by unindented** [comment]
Computering is hard.

**Comment by shri-bhat** [comment]
I have Python 2.7 but still getting same error.

 File "script\update-external-binaries.py", line 66, in <module>
   sys.exit(main())
 File "script\update-external-binaries.py", line 32, in main
   download_and_unzip('directxsdk-' + get_target_arch())
 File "script\update-external-binaries.py", line 50, in download_and_unzip
   zip_path = download_framework(framework)
 File "script\update-external-binaries.py", line 61, in download_framework
   download('Download ' + framework, url, path)
 File "C:\Shripad\Electron\Git\electron\script\lib\util.py", line 85, in download

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
