### ISSUE TITLE
Error bootstraping on OS X

### ISSUE THREAD

**Issue by ducky427** [atom-archive/electron-starter#51]
Hi,
I am running OS X 10.10.2. I installed node using homebrew and its the latest version (0.12.0) with the debugger hooks.

As it says in the README, I tried to run the bootstrap script. But I get the following errors:

```
Node: v0.12.0
npm: v2.6.0
Installing build modules...
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.6.0"})
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

/Users/.../atom-shell-starter/apm/node_modules/atom-package-manager/lib/auth.js:14
      throw error;
            ^
Error: Cannot find module '../build/Release/keytar.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/.../atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/Users/.../atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/keytar/lib/keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

If I run the boostrap command again, it doesn't print the warnings anymore but it still fails with the same stacktrace.

Any help would be appreciated.

Thanks!

**Comment by kevinsawicki** [comment]
Can you try removing the `build/node_modules` and `apm/node_modules` directories and bootstrapping again?

**Comment by DrMabuse23** [comment]
I got the same here i use ````brew switch node 0.10.35_2 script/clean script/bootstrap and still work

**Comment by ducky427** [comment]
@kevinsawicki, after deleting the two folders, I still get the same error:

```
Node: v0.12.0
npm: v2.6.0
Installing build modules...
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.6.0"})
child_process: customFds option is deprecated, use stdio instead.
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.6.0"})
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

/Users/.../atom-shell-starter/apm/node_modules/atom-package-manager/lib/auth.js:14
      throw error;
            ^
Error: Cannot find module '../build/Release/keytar.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/.../atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/Users/.../atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/keytar/lib/keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

@DrMabuse23 I don't have that version of node installed. Could you point me to how to install it using homebrew?

Thanks.

**Comment by DrMabuse23** [comment]
@ducky427 inread this before http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

**Comment by ducky427** [comment]
Thanks @DrMabuse23 

I installed 0.10.35 of node and it worked.

Maybe this issue should be documented.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
