### ISSUE TITLE
Error building on Ubuntu

### ISSUE THREAD

**Issue by bsr203** [atom-archive/electron-starter#81]
My macbook air is freezing as I build this starter, may be due to low memory. When trying on ubuntu, I get this error
Building on Ubuntu 14.04 LTS

```
script/build --verbose
Node: v0.10.38
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Initializing
Command-line options: --gruntfile=/home/julie/work/programming/electron/sample/electron-starter/build/Gruntfile.coffee, --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bower-task" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-bower-task/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-bower-task/package.json...OK
Loading "bower_task.js" tasks...OK
+ bower

Registering "grunt-coffeelint" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-coffeelint/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-coffeelint/package.json...OK
Loading "coffeelint.js" tasks...OK
+ coffeelint

Registering "grunt-lesslint" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-lesslint/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-lesslint/package.json...OK
Loading "less-lint-task.js" tasks...OK
+ lesslint
Loading "lint-utils.js" tasks...OK
>> No tasks were registered or unregistered.

Registering "grunt-cson" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-cson/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-cson/package.json...OK
Loading "cson-task.js" tasks...OK
+ cson

Registering "grunt-contrib-csslint" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-contrib-csslint/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-contrib-csslint/package.json...OK
Loading "csslint.js" tasks...OK
+ csslint

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-contrib-less" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-contrib-less/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-contrib-less/package.json...OK
Loading "less.js" tasks...OK
+ less

Registering "grunt-shell" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-shell/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell

Registering "grunt-build-atom-shell" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-build-atom-shell/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-build-atom-shell/package.json...OK
Loading "build-atom-shell-task.coffee" tasks...OK
+ build-atom-shell, rebuild-atom-shell, rebuild-native-modules
Loading "task-helpers.coffee" tasks...OK
>> No tasks were registered or unregistered.

Registering "grunt-atom-shell-installer" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-atom-shell-installer/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-atom-shell-installer/package.json...OK
Loading "index.js" tasks...OK
+ create-windows-installer

Registering "grunt-peg" local Npm module tasks.
Reading /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-peg/package.json...OK
Parsing /home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-peg/package.json...OK
Loading "peg.js" tasks...OK
+ peg

Registering "tasks" tasks.
Loading "build-task.coffee" tasks...OK
+ build
Loading "check-licenses-task.coffee" tasks...OK
+ check-licenses
Loading "clean-task.coffee" tasks...OK
+ clean, partial-clean
Loading "codesign-task.coffee" tasks...OK
+ codesign
Loading "copy-info-plist-task.coffee" tasks...OK
+ copy-info-plist
Loading "dump-symbols-task.coffee" tasks...OK
+ dump-symbols
Loading "generate-asar.coffee" tasks...OK
+ generate-asar
Loading "generate-license-task.coffee" tasks...OK
+ generate-license
Loading "install-task.coffee" tasks...OK
+ install
Loading "license-overrides.coffee" tasks...OK
>> No tasks were registered or unregistered.
Loading "mkdeb-task.coffee" tasks...OK
+ mkdeb
Loading "mkrpm-task.coffee" tasks...OK
+ mkrpm
Loading "output-disk-space.coffee" tasks...OK
+ output-disk-space
Loading "output-long-paths-task.coffee" tasks...OK
+ output-long-paths
Loading "set-exe-icon-task.coffee" tasks...OK
+ set-exe-icon
Loading "set-version-task.coffee" tasks...OK
+ set-version
Loading "spec-task.coffee" tasks...OK
+ run-specs
Loading "task-helpers.coffee" tasks...OK
>> No tasks were registered or unregistered.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ ci, compile, default, lint, test

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "build-atom-shell" task
Verifying properties build-atom-shell.buildDir, build-atom-shell.tag, build-atom-shell.projectName, build-atom-shell.productName exist in config...OK
>> Cloning to /tmp/eightoheight-build
>> Running: git clone https://github.com/atom/atom-shell atom-shell
>> Running: git fetch origin
>> Running: git reset --hard HEAD
>> Running: git checkout v0.24.0
>> Rigging atom.gyp to have correct name
Reading /tmp/eightoheight-build/atom-shell/atom.gyp...OK
Writing /tmp/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
>> Running: python script/build.py -c Release -t eightoheight
>> 
>> Rigging atom.gyp to have correct name
Reading /tmp/eightoheight-build/atom-shell/atom.gyp...OK
Writing /tmp/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
>> Running: python script/build.py -c Release -t eightoheight
>> 
Warning: null Use --force to continue.

Aborted due to warnings.
```

and `script/grunt --verbose --stack` gives

```
Running "build-atom-shell" task
Verifying properties build-atom-shell.buildDir, build-atom-shell.tag, build-atom-shell.projectName, build-atom-shell.productName exist in config...OK
>> Running: git remote set-url origin https://github.com/atom/atom-shell
>> Running: git fetch origin
>> Running: git reset --hard HEAD
>> Running: git checkout v0.24.0
>> Rigging atom.gyp to have correct name
Reading /tmp/eightoheight-build/atom-shell/atom.gyp...OK
Writing /tmp/eightoheight-build/atom-shell/atom.gyp...OK
>> bootstrap appears to have been run, skipping it to save time!
>> Running: python script/build.py -c Release -t eightoheight
>> 
>> Rigging atom.gyp to have correct name
Reading /tmp/eightoheight-build/atom-shell/atom.gyp...OK
Writing /tmp/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
>> Running: python script/build.py -c Release -t eightoheight
>> 
Warning: null Use --force to continue.
Error: null
  at ChildProcess.<anonymous> (/home/julie/work/programming/electron/sample/electron-starter/build/node_modules/grunt-build-atom-shell/tasks/task-helpers.coffee:67:37)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:766:16)
  at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by paulcbetts** [comment]
You're probably missing build dependencies:

```
apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    curl \
    git \
    fakeroot \
    clang \
    libgnome-keyring-dev \
    libnss3 \
    libgtk2.0-dev \
    libnotify-dev \
    libdbus-1-dev \
    libxrandr-dev \
    libxext-dev \
    libgconf2-dev \
    libasound2-dev \
    libcap-dev \
    libcups2-dev \
    libXtst-dev \
    --no-install-recommends
```

**Comment by bsr203** [comment]
@paulcbetts thanks for the response. I will try it out.

Can you please comment on what is the difference between the approach taken by this project, and by most other boilerplate where they just change the resource files in the Electron.App (I am in mac now, but hope the approach is same for other platforms). For example, please see https://github.com/szwacz/electron-boilerplate . This project claims support for all platforms, but doesn't involve the elaborate process of building the Electron executable from scratch. It would be a great if you can clarify what I can do additional through recompilation. 

thanks a ton,
bsr.

**Comment by paulcbetts** [comment]
> This project claims support for all platforms, but doesn't involve the elaborate process of building the Electron executable from scratch. It would be a great if you can clarify what I can do additional through recompilation.

Until recently, the only way to get native node modules working on Windows was to rebuild Electron. This project is also derived from the Atom / Slack build process so it has been production-tested. Basically all of these other projects dodge hard problems or ignore them and let their users find it out later :-/

**Comment by bsr203** [comment]
don't use this now. so closing.
