### ISSUE TITLE
msbuild.exe error while building on Windows 7

### ISSUE THREAD

**Issue by helarqjsc** [atom-archive/electron-starter#88]
Could you guys please help me to understand what am I doing wrong here?

```
$ script/build
Node: v0.12.4
npm: v1.4.28
Python: v2.7.9
Installing build modules...
npm WARN package.json eightoheight-build@ No license field.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\electron-starter\build\node_modules\runas
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\electron-starter\build\node_modules\asar\node_modules\chromium-pickle
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\electron-starter\build\node_modules\minidump
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\xampp\\htdocs\\electron-starter\\.npmrc" "install" "--quiet"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! runas@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\electron-starter\build\npm-debug.log
```

**Comment by maxkorp** [comment]
This "the system cannot find the path specified" seems to have happened recently, and seems triggered by install scripts. for example, i get a similar thing with both my project (originally based on this) and this currently at master at the root level. 

```
C:\Users\maxk\Development\electron-starter>script\bootstrap
Node: v0.10.38
npm: v2.11.3
Python: v2.7.9
Installing build modules...
npm WARN package.json eightoheight-build@ No license field.
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.10.38","npm":"2.11.3"})
Installing apm...
Installing modules failed
> eightoheight@0.0.1 preinstall C:\Users\maxk\Development\electron-starter
> node -e 'process.exit(0)'


The system cannot find the path specified.

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\maxk\\Development\\electron-starter\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "C:\\Users\\maxk\\Development\\electron-starter\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\maxk\\Development\\electron-starter\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\maxk\\.eightoheight\\.apmrc" "install" "--target=0.21.0" "--arch=ia32" "--quiet" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE
npm ERR! eightoheight@0.0.1 preinstall: `node -e 'process.exit(0)'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eightoheight@0.0.1 preinstall script 'node -e 'process.exit(0)''.
npm ERR! This is most likely a problem with the eightoheight package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e 'process.exit(0)'
npm ERR! You can get their info via:
npm ERR!     npm owner ls eightoheight
npm ERR! There is likely additional logging output above.
```

note that the failed command `node -e 'process.exit(0)'` is in the preinstall script. Removing that allows me further in (to where you are, actually). 2 other modules use a similar pattern, nslog and runas iirc. Removing both modules allows me to build successfully. I was thinking it was an NPM version issue, but you're using a much older npm version so I don't think thats it. I'm on an older node (0.10.38) but I don't think that's it either since youre on 12 (and that hasn't changed for me anyways).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
